# .github/release.yml
# ref: https://github.com/mizdra/eslint-interactive/blob/ae140c92081f8fb5c6d2cc3368ed5b186529981f/.github/release.yml

changelog:
  exclude:
    labels:
      - 'ignore for release'

  categories:
    - title: Breaking Change
      labels: ['Type: Breaking Change']
    - title: Bug
      labels: ['Type: Bug']
    - title: Documentation
      labels: ['Type: Documentation']
    - title: Feature
      labels: ['Type: Feature']
    - title: Refactoring
      labels: ['Type: Refactoring']
    - title: Testing
      labels: ['Type: Testing']
    - title: Maintenance
      labels: ['Type: Maintenance']
    - title: CI
      labels: ['Type: CI']
    - title: Question
      labels: ['Type: Question']
    - title: Security
      labels: ['Type: Security']
    - title: Dependencies
      labels: ['Type: Dependencies']

    - title: Other Changes
      labels: ['*']